#!/usr/bin/env python3

import argparse
import sys
import os
import math

from codeutil import *

PATH = os.getcwd() + "/"

def main():
    global ext
    global templates
    parser = argparse.ArgumentParser(description="Turing compiler")
    parser.add_argument("--language", "-l", default="c++", choices=ext.keys(), help="The language to be used.") 
    parser.add_argument("problem_name", help="The problem name to be used when generating the files.")
    args = parser.parse_args()
    name = args.problem_name
    lang = args.language
    try:
        os.mkdir(name)
    except FileExistsError:
        print("Folder " + name + " already exists. Please remove it first.", file=sys.stderr)
        return 2
    to_create = [ext[lang], "in", "out", "err"]
    os.system("touch " + " ".join([name + "/" + name + "." + x for x in to_create]))
    os.system("cd " + name + " && echo -e \"" + templates[lang].format(name) + "\" > " + name + "." + to_create[0])
    os.system("cd " + name + " && nvim -p " + " ".join([name + "." + x for x in to_create]))

if __name__ == "__main__":
    try:
        sys.exit(main())
    except KeyboardInterrupt:
        sys.exit(1)
