#!/usr/bin/env python3

import argparse
import os
import pipes


class Server:
    def __init__(self, hostname, address, user, port, identity):
        self.hostname = hostname
        self.address = address
        self.port = port
        self.identity = identity
        self.user = user

    def format(self, location):
        return '{0}@{1}:{2}'.format(self.user, self.address, pipes.quote(location.split(self.hostname + ':', 1)[-1]))


servers = {}


def scp(source, destination):
    if ':' in source:
        source_server = servers[source.split(':')[0]]
        port = source_server.port
        identity = source_server.identity
        source = source_server.format(source)
    if ':' in destination:
        destination_server = servers[destination.split(':')[0]]
        port = destination_server.port
        identity = destination_server.identity
        destination = destination_server.format(destination)

    source = pipes.quote(source)
    destination = pipes.quote(destination)

    os.system(
        'scp -r -i {identity} -P {port} {source} {destination}'.format(
            identity=identity,
            port=port,
            source=source,
            destination=destination,
        ),
    )


with open(os.path.join(os.environ['HOME'], '.ssh', 'config'), 'r') as f:
    for x in f.read().strip().split('\n\n'):
        settings = {
            'port': 22,
            'identity': '~/.ssh/id_rsa',
        }
        for y in x.strip().split('\n'):
            key, value = y.split()
            settings[key.lower()] = value
        servers[settings['host']] = Server(
            hostname=settings['host'],
            address=settings['hostname'],
            user=settings['user'],
            port=settings['port'],
            identity=settings['identity'],
        )


def check_server(location):
    if ':' in location and location.split(':')[0] not in servers:
        raise argparse.ArgumentTypeError('Unknown hostname "{}"'.format(location.split(':')[0]))
    return location


parser = argparse.ArgumentParser(description='SCP Wrapper')
parser.add_argument('source', help='Source location.', type=check_server)
parser.add_argument('destination', help='Destination location.', type=check_server)

args = parser.parse_args()
scp(args.source, args.destination)
