#!/usr/bin/env python3

import argparse
import re
import subprocess


rerange = re.compile(r'\d+-\d+')


def page_group(val):
    if rerange.match(val):
        return str(val)
    raise ValueError('Invalid range "%s"' % val)


def main():
    parser = argparse.ArgumentParser(description='Split PDF pages.')
    parser.add_argument('pdf_file', type=str)
    parser.add_argument('--start', '-s', type=int, default=1, help='Start index')
    parser.add_argument('page_groups', type=page_group, nargs='+', help='Page groups')
    args = parser.parse_args()

    for index, group in enumerate(args.page_groups, args.start):
        subprocess.run(
            ['qpdf', '--empty', '--pages', args.pdf_file, group, '--', 'p%d.pdf' % index]
        )


if __name__ == '__main__':
    main()
